# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: false
disqus_shortname:

# utterances comment
utterances: false
utterances_repo:

# livere city comment
livere: false
livere_data_uid:

# giscus comment
giscus: false
data_repo:
data_repo_id:
data_category:
data_category_id:
data_mapping:
#data_term:
data_strict: 0
data_reactions_enabled: 0
data_emit_metadata: 0
data_input_position: bottom
data_loading:
data_lang:

# google analytics
googleTrackId:

# baidu analytics
baiduTrackId:

theme_config:
  read_more_btn: true

menu:
  Home: /
  Archives: /archives
  Categories: /categories
  Tags: /tags